const ROLES = {
  STUDENT: 'STUDENT',
  COUNSELLOR: 'COUNSELLOR',
  ADMIN: 'ADMIN'
};

const CONSENT_TYPES = {
  WELLBEING_CHECKIN: 'wellbeing_checkin',
  FINANCIAL_MATCHING: 'financial_matching',
  ACADEMIC_INTEGRATION: 'academic_integration',
  ACADEMIC_DATA: 'academic_data',
  AI_SUPPORT: 'ai_support'
};

const SUPPORT_LEVELS = {
  LOW: 'LOW',
  MILD: 'MILD',
  MODERATE: 'MODERATE',
  HIGH: 'HIGH'
};

const SUPPORT_CATEGORIES = {
  ACADEMIC: 'ACADEMIC',
  FINANCIAL: 'FINANCIAL',
  WELLBEING: 'WELLBEING'
};

const FINANCIAL_DIFFICULTY = {
  NONE: 'NONE',
  SLIGHT: 'SLIGHT',
  MODERATE: 'MODERATE',
  SIGNIFICANT: 'SIGNIFICANT',
  PREFER_NOT_TO_SAY: 'PREFER_NOT_TO_SAY'
};

const EXPENSE_CATEGORIES = {
  TUITION: 'TUITION',
  HOSTEL: 'HOSTEL',
  FOOD: 'FOOD',
  BOOKS: 'BOOKS',
  TRANSPORT: 'TRANSPORT',
  EXAM_FEES: 'EXAM_FEES',
  OTHER: 'OTHER'
};

const AID_STATUS = {
  RECEIVING: 'RECEIVING',
  NOT_RECEIVING: 'NOT_RECEIVING',
  APPLIED_WAITING: 'APPLIED_WAITING',
  PREFER_NOT_TO_SAY: 'PREFER_NOT_TO_SAY'
};

const APPOINTMENT_STATUS = {
  REQUESTED: 'REQUESTED',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  FOLLOW_UP: 'FOLLOW_UP',
  CLOSED: 'CLOSED'
};

const MODERATION_STATUS = {
  APPROVED: 'APPROVED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  FLAGGED_HIGH_RISK: 'FLAGGED_HIGH_RISK'
};

const CORRECTION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const DEFAULT_CONFIG = {
  CAMPUS_SUPPORT_NAME: process.env.CAMPUS_SUPPORT_NAME || 'Nivara Campus Well-being Center',
  CAMPUS_SUPPORT_HOURS: process.env.CAMPUS_SUPPORT_HOURS || 'Monday - Friday, 9:00 AM - 6:00 PM',
  CAMPUS_SUPPORT_LOCATION: process.env.CAMPUS_SUPPORT_LOCATION || 'Student Care Block, 2nd Floor, Room 204',
  CRISIS_HELPLINE_INFO: process.env.CRISIS_HELPLINE_INFO || 'National Tele-MANAS (14416 / 1800-891-4416) or Campus Emergency Support'
};

module.exports = {
  ROLES,
  CONSENT_TYPES,
  SUPPORT_LEVELS,
  SUPPORT_CATEGORIES,
  FINANCIAL_DIFFICULTY,
  EXPENSE_CATEGORIES,
  AID_STATUS,
  APPOINTMENT_STATUS,
  MODERATION_STATUS,
  CORRECTION_STATUS,
  DEFAULT_CONFIG
};
